### ISSUE TITLE
Python3 install error

### ISSUE THREAD

**Issue by osallou** [stewrutledge/gelfHandler#6]
Hi,
when installing gelfHandler with python3, an error is raised

```
Running setup.py install for gelfHandler
    File "/home/ubuntu/virtualenv/python3.3/lib/python3.3/site-packages/gelfHandler/gelf.py", line 35
      print "connecting via tcp" # DEBUG
                               ^
  SyntaxError: invalid syntax
```

There might be other issues. Could you check/upload of python2/3 compatible package?

**Comment by stewrutledge** [comment]
I've worked on this code a bit and it SHOULD be working with 2.7-3.5.
